alias Hakkawine.DatabaseSeeder
alias Hakkawine.Infra.OBFSDomain

domains = [
  %{domain: "microsoft.com", is_blocked: false},
  %{domain: "bing.com", is_blocked: false},
  %{domain: "outlook.live.com", is_blocked: false},
  %{domain: "msn.com", is_blocked: false},
  %{domain: "office.com", is_blocked: false},
  %{domain: "windows.net", is_blocked: false},
  %{domain: "azure.microsoft.com", is_blocked: false},
  %{domain: "apple.com", is_blocked: false},
  %{domain: "mzstatic.com", is_blocked: false},
  %{domain: "apps.apple.com", is_blocked: false},
  %{domain: "itunes.apple.com", is_blocked: false},
  %{domain: "icloud.com", is_blocked: false},
  %{domain: "icloud-content.com", is_blocked: false},
  %{domain: "amazon.com", is_blocked: false},
  %{domain: "amazonaws.com", is_blocked: false},
  %{domain: "www.adobe.com", is_blocked: false},
  %{domain: "adobe.io", is_blocked: false},
  %{domain: "acrobat.com", is_blocked: false},
  %{domain: "baidu.com", is_blocked: false},
  %{domain: "bdstatic.com", is_blocked: false},
  %{domain: "bdimg.com", is_blocked: false},
  %{domain: "alibabagroup.com", is_blocked: false},
  %{domain: "alibabacloud.com", is_blocked: false},
  %{domain: "taobao.com", is_blocked: false},
  %{domain: "tencent.com", is_blocked: false},
  %{domain: "qcloud.com", is_blocked: false},
  %{domain: "qq.com", is_blocked: false},
  %{domain: "bytedance.com", is_blocked: false},
  %{domain: "snssdk.com", is_blocked: false},
  %{domain: "volcengine.com", is_blocked: false},
  %{domain: "netease.com", is_blocked: false},
  %{domain: "163.com", is_blocked: false},
  %{domain: "126.net", is_blocked: false},
  %{domain: "mihoyo.com", is_blocked: false},
  %{domain: "hoyoverse.com", is_blocked: false},
  %{domain: "shein.com", is_blocked: false},
  %{domain: "temu.com", is_blocked: false},
  %{domain: "pinduoduo.com", is_blocked: false},
  %{domain: "huawei.com", is_blocked: false},
  %{domain: "huaweicloud.com", is_blocked: false},
  %{domain: "mi.com", is_blocked: false},
  %{domain: "xiaomi.com", is_blocked: false},
  %{domain: "tesla.com", is_blocked: false},
  %{domain: "tesla.cn", is_blocked: false},
  %{domain: "nvidia.com", is_blocked: false},
  %{domain: "intel.com", is_blocked: false},
  %{domain: "amd.com", is_blocked: false},
  %{domain: "steampowered.com", is_blocked: false},
  %{domain: "epicgames.com", is_blocked: false},
  %{domain: "riotgames.com", is_blocked: false},
  %{domain: "ea.com", is_blocked: false},
  %{domain: "ubisoft.com", is_blocked: false},
  %{domain: "blizzard.com", is_blocked: false},
  %{domain: "activision.com", is_blocked: false},
  %{domain: "rockstargames.com", is_blocked: false},
  %{domain: "take2games.com", is_blocked: false},
  %{domain: "capcom.com", is_blocked: false},
  %{domain: "square-enix.com", is_blocked: false},
  %{domain: "bandainamcoent.com", is_blocked: false},
  %{domain: "www.sega.com", is_blocked: false},
  %{domain: "supercell.com", is_blocked: false},
  %{domain: "xbox.com", is_blocked: false},
  %{domain: "playstation.com", is_blocked: false},
  %{domain: "nintendo.com", is_blocked: false},
  %{domain: "sony.com", is_blocked: false},
  %{domain: "cloudflare.com", is_blocked: false},
  %{domain: "akamai.com", is_blocked: false},
  %{domain: "fastly.com", is_blocked: false},
  %{domain: "fastly.net", is_blocked: false},
  %{domain: "stackpath.com", is_blocked: false},
  %{domain: "cdn77.com", is_blocked: false},
  %{domain: "gcore.com", is_blocked: false},
  %{domain: "bunny.net", is_blocked: false},
  %{domain: "keycdn.com", is_blocked: false}
]

DatabaseSeeder.seed(
  OBFSDomain,
  :domain,
  domains,
  update_fields: [:is_blocked]
)
