CREATE TYPE user_account_type AS ENUM('customer', 'staff', 'system_admin');

CREATE TYPE user_status AS ENUM('unverified', 'active', 'suspended', 'deactivating');

CREATE TABLE user_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type user_account_type NOT NULL DEFAULT 'customer',
    status user_status NOT NULL DEFAULT 'unverified',
    email varchar(255) NOT NULL,
    -- RFC standard max length is 254.
    password_hash varchar(255) NOT NULL,
    -- 255 is safe for argon2 hashes
    language varchar(10) NOT NULL DEFAULT 'en',
    email_verified_at timestamptz,
    password_updated_at timestamptz,
    telegram_chat_id bigint,
    invited_by bigint,
    invite_code varchar(16),
    invite_count int NOT NULL DEFAULT 0,
    suspended_until timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_user_accounts_active_email ON user_accounts (email);

CREATE UNIQUE INDEX uk_user_accounts_invite_code ON user_accounts (invite_code);

CREATE INDEX idx_user_accounts_invited_by ON user_accounts (invited_by);