CREATE TYPE rule_type AS ENUM('first_order_percent', 'all_order_percent');

CREATE TABLE commission_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    rule_type rule_type NOT NULL,
    reward_rate DECIMAL(5, 4) NOT NULL DEFAULT 0,
    user_id bigint DEFAULT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE settlement_status AS ENUM('pending', 'unlocked', 'cancelled');

CREATE TABLE commission_settlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id bigint NOT NULL,
    buyer_id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_amount DECIMAL(38, 18) NOT NULL,
    commission_rate DECIMAL(5, 4) NOT NULL,
    commission_amount DECIMAL(38, 18) NOT NULL,
    status settlement_status NOT NULL DEFAULT 'pending',
    freeze_days int NOT NULL DEFAULT 30,
    unlock_at timestamptz NOT NULL,
    unlocked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_settlements_unlock ON commission_settlements (status, unlock_at) WHERE status = 'pending';
CREATE INDEX idx_settlements_order ON commission_settlements (order_id);

CREATE TABLE user_commissions (
    user_id bigint PRIMARY KEY,
    commission_balance DECIMAL(38, 18) NOT NULL DEFAULT 0,
    total_earned DECIMAL(38, 18) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE commission_log_type AS ENUM('referral_reward', 'milestone_reward', 'transfer_to_balance', 'withdraw_payout', 'withdraw_reject_refund');

CREATE TABLE commission_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    action_type commission_log_type NOT NULL,
    before_amount DECIMAL(38, 18) NOT NULL,
    amount DECIMAL(38, 18) NOT NULL,
    after_amount DECIMAL(38, 18) NOT NULL,
    settlement_id bigint,
    withdrawal_id bigint,
    remark varchar(255),
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_commission_logs_user ON commission_logs (user_id, created_at DESC);

CREATE TABLE payout_channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_method varchar(32) NOT NULL, 
    -- for frontend: balance/manual_transfer/alipay/wechat/usdt_trc20
    payout_driver varchar(32) NOT NULL, 
    -- for backend: balance/manual/epay_payout/alipay_api/usdt_trc20_api
    name varchar(64) NOT NULL,
    icon_url varchar(255),
    min_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    max_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    handling_fee_fixed DECIMAL(38, 18) NOT NULL DEFAULT 0,
    handling_fee_percent DECIMAL(38, 18) NOT NULL DEFAULT 0,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_enable boolean NOT NULL DEFAULT TRUE,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE withdrawal_status AS ENUM('pending', 'approved', 'completed', 'rejected');

CREATE TABLE withdrawal_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sn varchar(64) NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    payout_channel_id bigint,
    payout_method varchar(32) NOT NULL,
    payout_driver varchar(32) NOT NULL,
    currency varchar(16) NOT NULL DEFAULT 'USD',
    amount DECIMAL(38, 18) NOT NULL,
    handling_fee DECIMAL(38, 18) NOT NULL DEFAULT 0,
    actual_amount DECIMAL(38, 18) NOT NULL,
    payout_account varchar(255) NOT NULL,
    payout_identity jsonb DEFAULT '{}'::jsonb,
    status withdrawal_status NOT NULL DEFAULT 'pending',
    reject_reason varchar(255),
    payout_trade_no varchar(128),
    handled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_withdrawals_user ON withdrawal_records (user_id, status);
CREATE INDEX idx_withdrawals_created_at ON withdrawal_records (created_at);