CREATE TABLE payment_gateways (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_driver varchar(32) NOT NULL,
    -- balance/manual_transfer/epay/alipay_private/usdt_trc20
    name varchar(64) NOT NULL,
    icon_url varchar(255),
    handling_fee_fixed DECIMAL(38, 18) NOT NULL DEFAULT 0,
    handling_fee_percent DECIMAL(38, 18) NOT NULL DEFAULT 0,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_enable boolean NOT NULL DEFAULT TRUE,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE payment_record_status AS ENUM('pending', 'paid', 'failed', 'expired', 'refunded');

CREATE TABLE payment_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_no varchar(128) NOT NULL UNIQUE,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    payment_gateway_id bigint NOT NULL,
    payment_driver varchar(32) NOT NULL,
    gateway_trade_no varchar(128),
    callback_payload jsonb,
    order_amount DECIMAL(38, 18) NOT NULL,
    handling_fee DECIMAL(38, 18) NOT NULL DEFAULT 0,
    total_amount DECIMAL(38, 18) NOT NULL,
    gateway_currency varchar(16) NOT NULL,
    gateway_amount DECIMAL(38, 18) NOT NULL,
    status payment_record_status NOT NULL DEFAULT 'pending',
    paid_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payment_records_order ON payment_records (order_id);
CREATE INDEX idx_payment_records_user ON payment_records (user_id, status);
CREATE UNIQUE INDEX uk_payment_records_gateway_trade ON payment_records (payment_gateway_id, gateway_trade_no) WHERE gateway_trade_no IS NOT NULL;

CREATE TABLE user_balances (
    user_id bigint PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    balance DECIMAL(38, 18) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE balance_log_type AS ENUM('recharge', 'recharge_bonus', 'order_payment', 'order_refund', 'commission_transfer', 'system_bonus', 'system_deduct');

CREATE TABLE user_balance_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    action_type balance_log_type NOT NULL,
    before_balance DECIMAL(38, 18) NOT NULL,
    amount DECIMAL(38, 18) NOT NULL,
    after_balance DECIMAL(38, 18) NOT NULL,
    ref_type varchar(50) NOT NULL,
    ref_id bigint NOT NULL,
    operator_id bigint,
    remark varchar(255),
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_balance_logs_user_id ON user_balance_logs (user_id, created_at DESC);