CREATE TYPE order_type AS ENUM('plan_purchase', 'plan_renew', 'plan_upgrade', 'traffic_reset_fee', 'traffic_addon', 'balance_recharge');

CREATE TYPE order_status AS ENUM('pending', 'processing', 'completed', 'cancelled', 'failed', 'refunded', 'disputed');

CREATE TYPE billing_cycle AS ENUM('monthly', 'quarterly', 'half_yearly', 'yearly', 'one_time');

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    type order_type NOT NULL DEFAULT 'plan_purchase',
    status order_status NOT NULL DEFAULT 'pending',
    product_id bigint,
    product_price_id bigint,
    subscription_id bigint,
    billing_cycle billing_cycle,
    subtotal_amount DECIMAL(38, 18) NOT NULL,
    discount_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    balance_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    payment_fee DECIMAL(38, 18) NOT NULL DEFAULT 0,
    total_amount DECIMAL(38, 18) NOT NULL,
    coupon_code varchar(32),
    coupon_snapshot jsonb,
    price_snapshot jsonb,
    payment_method_id bigint,
    payment_driver varchar(32), -- balance/manual_transfer/epay
    paid_at timestamptz,
    note text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_orders_order_no ON orders (order_no);

CREATE INDEX idx_orders_user_status_created ON orders (user_id, status, created_at DESC);

CREATE TABLE payment_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(32) NOT NULL UNIQUE,
    payment_driver varchar(32) NOT NULL, -- balance/manual_transfer/epay
    name varchar(64) NOT NULL,
    description varchar(255) NOT NULL,
    icon_url varchar(255) NOT NULL,
    min_tx_amount DECIMAL(38, 18) DEFAULT NULL,
    max_tx_amount DECIMAL(38, 18) DEFAULT NULL,
    handling_fee_fixed DECIMAL(38, 18),
    handling_fee_percent DECIMAL(38, 18),
    is_enable boolean NOT NULL DEFAULT TRUE,
    is_visible boolean NOT NULL DEFAULT TRUE,
    is_default boolean NOT NULL DEFAULT FALSE,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE payment_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_method_id bigint NOT NULL,
    name varchar(64) NOT NULL,
    is_enable boolean NOT NULL DEFAULT TRUE,
    weight int NOT NULL DEFAULT 1,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    min_tx_amount DECIMAL(38, 18) DEFAULT NULL,
    max_tx_amount DECIMAL(38, 18) DEFAULT NULL,
    daily_limit_amount DECIMAL(38, 18) DEFAULT NULL,
    daily_accumulated_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    daily_limit_count int DEFAULT NULL,
    daily_accumulated_count int NOT NULL DEFAULT 0,
    yearly_limit_amount DECIMAL(38, 18) DEFAULT NULL,
    yearly_accumulated_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    last_daily_reset_at timestamptz NOT NULL DEFAULT NOW(),
    last_yearly_reset_at timestamptz NOT NULL DEFAULT NOW(),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payment_accounts_gateway ON payment_accounts (payment_method_id, is_enable);

CREATE TYPE payment_record_status AS ENUM('pending', 'paid', 'failed', 'expired', 'refunded');

CREATE TABLE payment_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_no varchar(128) NOT NULL,
    gateway_trade_no varchar(128),
    status payment_record_status NOT NULL DEFAULT 'pending',
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    payment_method_id bigint NOT NULL,
    payment_account_id bigint NOT NULL,
    payment_driver varchar(32) NOT NULL,
    amount DECIMAL(38, 18) NOT NULL,
    gateway_currency varchar(16) NOT NULL,
    gateway_amount DECIMAL(38, 18) NOT NULL,
    callback_payload jsonb,
    paid_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_payment_records_trade_no ON payment_records (trade_no);

CREATE UNIQUE INDEX uk_payment_records_gateway_trade ON payment_records (payment_method_id, gateway_trade_no) WHERE gateway_trade_no IS NOT NULL;

CREATE INDEX idx_payment_records_order_status ON payment_records (order_id, status);

CREATE INDEX idx_payment_records_user_status_created ON payment_records (user_id, status, created_at DESC);

CREATE TABLE user_balances (
    user_id bigint PRIMARY KEY,
    balance DECIMAL(38, 18) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE balance_log_type AS ENUM('recharge', 'recharge_bonus', 'order_payment', 'order_refund', 'commission_transfer', 'system_bonus', 'system_deduct');

CREATE TABLE user_balance_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    action_type balance_log_type NOT NULL,
    before_balance DECIMAL(38, 18) NOT NULL,
    amount DECIMAL(38, 18) NOT NULL,
    after_balance DECIMAL(38, 18) NOT NULL,
    ref_type varchar(50) NOT NULL, -- orders/payment_records/user_commissions
    ref_id bigint NOT NULL,
    operator_id bigint,
    remark varchar(255),
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_balance_logs_user_id ON user_balance_logs (user_id, created_at DESC);