CREATE TYPE product_type AS ENUM('plan', 'addon');

CREATE TYPE product_status AS ENUM('draft', 'active', 'archived');

CREATE TYPE charge_type AS ENUM('recurring', 'one_time');

-- Note: Versioning is not implemented yet. Do not update or delete active plans directly to avoid breaking existing subscriptions.
CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(64) NOT NULL,
    description text,
    type product_type NOT NULL DEFAULT 'plan',
    status product_status NOT NULL DEFAULT 'draft',
    charge_type charge_type NOT NULL DEFAULT 'recurring',
    is_recommended boolean NOT NULL DEFAULT FALSE,
    sort_order int NOT NULL DEFAULT 0,
    traffic_quota_bytes bigint,
    limit_device_count int,
    limit_speed_mbps int,
    limit_speed_up_mbps int,
    limit_speed_down_mbps int,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_products_code_unique_draft_active ON products (code, status) WHERE status IN ('draft', 'active');

CREATE TYPE price_type AS ENUM( 'monthly', 'quarterly', 'half_yearly', 'yearly', 'onetime', 'reset');

CREATE TABLE product_prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    type price_type NOT NULL DEFAULT 'monthly',
    amount DECIMAL(38, 18) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_product_prices_product_id ON product_prices (product_id);

CREATE TABLE plan_slots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    slot_name varchar(32) NOT NULL, -- selects only one node
    selector jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX uk_plan_slots_product_slot_name ON plan_slots (product_id, slot_name);