CREATE TYPE content_status AS ENUM('draft', 'published', 'archived');

CREATE TABLE announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_pinned boolean NOT NULL DEFAULT FALSE,
    status content_status NOT NULL DEFAULT 'published',
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_announcements_front ON announcements (is_pinned DESC, updated_at DESC) WHERE status = 'published';

CREATE TABLE announcement_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id bigint NOT NULL,
    language varchar(10) NOT NULL, -- 'en', 'zh-Hans', 'zh-Hant', 'ja', 'ko'
    title varchar(255) NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_announcement_trans_lang ON announcement_translations (announcement_id, LANGUAGE);

CREATE TABLE articles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status content_status NOT NULL DEFAULT 'published',
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_articles_front ON articles (updated_at DESC) WHERE status = 'published';

CREATE TABLE article_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id bigint NOT NULL,
    language varchar(10) NOT NULL, -- 'en', 'zh-Hans', 'zh-Hant', 'ja', 'ko'
    title varchar(255) NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_article_trans_lang ON article_translations (article_id, LANGUAGE);