CREATE TABLE obfs_domains (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(255) NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_obfs_domains_domain on obfs_domains(domain);

CREATE TYPE node_status AS ENUM('pending', 'active', 'offline', 'disabled');

CREATE TYPE endpoint_pick_strategy AS ENUM (
    'pick_first',
    'prefer_ipv4',
    'prefer_ipv6',
    'prefer_domain',
    'pick_random'
);

CREATE TABLE nodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(32) NOT NULL,
    secret_hash varchar(255) NOT NULL,
    status node_status NOT NULL DEFAULT 'pending',
    endpoints varchar(255)[] NOT NULL, -- IPv4 / IPv6 / domain (max 10 addresses)
    pick_strategy endpoint_pick_strategy NOT NULL DEFAULT "pick_first",
    protocol varchar(16) NOT NULL, -- shadowsocks/anytls/hy2/vless+reality
    port_base int NOT NULL,
    stat_base int NOT NULL,
    port_capacity int NOT NULL DEFAULT 4096,
    cpu_cores int,
    ram_mb int,
    ssd_mb int,
    bandwidth_mbps int,
    monthly_traffic_bytes bigint,
    traffic_reset_day int NOT NULL DEFAULT 1,
    weight int NOT NULL DEFAULT 1,
    max_slot_count int NOT NULL,
    rate DECIMAL(5, 4) NOT NULL DEFAULT 1.00, -- 0.0001 - 9.9999
    labels jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_nodes_name ON nodes (name);

CREATE INDEX idx_nodes_status ON nodes (status);

CREATE INDEX idx_nodes_labels ON nodes USING GIN (labels);

CREATE TABLE node_leases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    plan_slot_id bigint NOT NULL,
    port int NOT NULL,
    proxy_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_node_leases_sub_slot ON node_leases(subscription_id, plan_slot_id)

CREATE INDEX idx_node_leases_node_id ON node_leases (node_id) WHERE is_active = TRUE;
