CREATE TYPE coupon_type AS ENUM('fixed_amount', 'percentage');

CREATE TABLE coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(32) NOT NULL,
    name varchar(64) NOT NULL,
    type coupon_type NOT NULL,
    value DECIMAL(38, 18) NOT NULL,
    limit_use_count int DEFAULT 0,
    used_count int NOT NULL DEFAULT 0,
    limit_user_use_count int DEFAULT 1,
    start_at timestamptz,
    end_at timestamptz,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_coupons_code ON coupons (code);

CREATE TABLE user_checkins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    traffic_amount int NOT NULL,
    check_in_date date NOT NULL,
    subscription_id bigint,
    applied_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_user_checkin_date ON user_checkins (user_id, check_in_date);