CREATE TABLE obfs_domains (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(255) NOT NULL UNIQUE,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TYPE node_status AS ENUM('pending', 'active', 'offline', 'disabled');
CREATE TYPE endpoint_pick_strategy AS ENUM (
    'pick_first',
    'prefer_ipv4',
    'prefer_ipv6',
    'prefer_domain',
    'pick_random'
);

CREATE TABLE nodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(32) NOT NULL,
    secret_hash varchar(255) NOT NULL,
    status node_status NOT NULL DEFAULT 'pending',
    endpoints varchar(255)[] NOT NULL, -- IPv4 / IPv6 / domain (max 10 addresses)
    pick_strategy endpoint_pick_strategy NOT NULL,
    protocol varchar(16) NOT NULL, -- shadowsocks/anytls/hy2/vless+reality
    port_base int NOT NULL,
    stat_base int NOT NULL,
    port_capacity int NOT NULL DEFAULT 4096,
    cpu_cores smallint,
    ram_mb int,
    ssd_mb int,
    bandwidth_mbps int DEFAULT 0,
    monthly_traffic_bytes bigint DEFAULT 0,
    traffic_reset_day smallint NOT NULL DEFAULT 1,
    weight int NOT NULL DEFAULT 1,
    max_slot_count int NOT NULL,
    rate DECIMAL(5, 4) NOT NULL DEFAULT 1.00, -- 0.0001 - 9.9999
    labels jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_nodes_name ON nodes (name);
CREATE INDEX idx_nodes_status ON nodes (status);
CREATE INDEX idx_nodes_labels ON nodes USING GIN (labels);

CREATE TABLE node_leases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    plan_slot_id bigint NOT NULL,
    auth_pass varchar(128),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_subscription_slot UNIQUE (subscription_id, plan_slot_id)
);

CREATE INDEX idx_node_leases_node_id ON node_leases (node_id) WHERE is_active = TRUE;
CREATE INDEX idx_node_leases_sub_id ON node_leases (subscription_id);

CREATE TYPE task_status AS ENUM('pending', 'processing', 'completed', 'failed');
CREATE TYPE task_action AS ENUM('upsert_user', 'delete_user');

CREATE TABLE node_sync_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    user_id bigint NOT NULL,
    action task_action NOT NULL,
    payload jsonb NOT NULL,
    status task_status NOT NULL DEFAULT 'pending',
    retry_count int NOT NULL DEFAULT 0,
    max_retries int NOT NULL DEFAULT 5,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_node_tasks_pending ON node_sync_tasks (node_id) WHERE status IN ('pending', 'processing');

CREATE TABLE node_traffic_logs (
    recorded_at timestamptz NOT NULL,
    node_id bigint NOT NULL,
    unique_id varchar(64) NOT NULL,
    -- md5(recorded_at + subscription_id + client_ip)
    user_id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    client_ip inet NOT NULL,
    upload_bytes bigint NOT NULL DEFAULT 0,
    download_bytes bigint NOT NULL DEFAULT 0,
    rate DECIMAL(5, 4) NOT NULL DEFAULT 1.0,
    PRIMARY KEY (recorded_at, node_id, unique_id)
);

SELECT create_hypertable ('node_traffic_logs','recorded_at');

ALTER TABLE node_traffic_logs
SET
    (
        timescaledb.compress,
        timescaledb.compress_segmentby = 'node_id,subscription_id,user_id',
        timescaledb.compress_orderby = 'recorded_at DESC'
    );

SELECT
    add_compression_policy ('node_traffic_logs', INTERVAL '7 days');

SELECT
    add_retention_policy ('node_traffic_logs', INTERVAL '14 days');

CREATE MATERIALIZED VIEW
    node_traffic_logs_5m
WITH
    (timescaledb.continuous) AS
SELECT
    time_bucket ('5 minutes', recorded_at)              AS bucket_5m,
    node_id,
    user_id,
    subscription_id,
    SUM(upload_bytes)                                   AS upload_bytes,
    SUM(download_bytes)                                 AS download_bytes,
    SUM(upload_bytes * rate)::bigint                    AS rated_upload_bytes,
    SUM(download_bytes * rate)::bigint                  AS rated_download_bytes,
    SUM((upload_bytes + download_bytes) * rate)::bigint AS rated_total_bytes
FROM
    node_traffic_logs
GROUP BY
    bucket_5m,
    node_id,
    user_id,
    subscription_id;

SELECT
    add_continuous_aggregate_policy (
        'node_traffic_logs_5m',
        start_offset = > INTERVAL '3 hours',
        end_offset = > INTERVAL '5 minutes',
        schedule_interval = > INTERVAL '5 minutes'
    );

SELECT
    add_retention_policy ('node_traffic_logs_5m', INTERVAL '38 days');

CREATE MATERIALIZED VIEW
    node_traffic_logs_daily
WITH
    (timescaledb.continuous) AS
SELECT
    time_bucket ('1 day', recorded_at)                  AS bucket_day,
    node_id,
    user_id,
    subscription_id,
    SUM(upload_bytes)                                   AS upload_bytes,
    SUM(download_bytes)                                 AS download_bytes,
    SUM(upload_bytes * rate)::bigint                    AS rated_upload_bytes,
    SUM(download_bytes * rate)::bigint                  AS rated_download_bytes,
    SUM((upload_bytes + download_bytes) * rate)::bigint AS rated_total_bytes
FROM
    node_traffic_logs
GROUP BY
    bucket_day,
    node_id,
    user_id,
    subscription_id;

SELECT
    add_continuous_aggregate_policy (
        'node_traffic_logs_daily',
        start_offset = > INTERVAL '7 days',
        end_offset = > INTERVAL '1 day',
        schedule_interval = > INTERVAL '1 hour'
    );

SELECT
    add_retention_policy ('node_traffic_logs_daily', INTERVAL '395 days');