-- ==============================================================================
-- Message Type (type) and Event Code (code) Mapping List
-- ==============================================================================
-- ------------------------------------------------------------------------------
-- 1. Authentication Category (type = 'auth')
-- Sent via Email/SMS only; synchronous security credentials; NEVER stored in user_notifications
-- ------------------------------------------------------------------------------
-- auth_register_code      : Account registration verification code
-- auth_reset_pwd_code     : Password reset verification code
-- auth_bind_email_code    : Email binding / changing verification code
-- auth_login_alert        : Unrecognized or unusual login security alert
-- ------------------------------------------------------------------------------
-- 2. Business Status Category (type = 'business')
-- Automated business events; multi-channel delivery (Email/TG/SMS + In-App Msg); uses message_templates
-- ------------------------------------------------------------------------------
-- sub_expiring_soon       : Subscription expiring in N days warning
-- sub_expired             : Subscription expired and service suspended notification
-- traffic_exhausted       : Data usage reached 90% / 100% alert
-- order_created           : New order created / pending payment reminder
-- order_paid_success      : Payment received and order completed confirmation
-- commission_received     : Referral commission credited notification
-- ------------------------------------------------------------------------------
-- 3. Customer Ticket Category (type = 'ticket')
-- Support interaction events; multi-channel delivery (Email/TG + In-App Msg); uses message_templates
-- ------------------------------------------------------------------------------
-- ticket_created          : Ticket submission confirmation
-- ticket_replied          : Support agent replied to the ticket
-- ticket_closed           : Ticket closed notification
-- ------------------------------------------------------------------------------
-- 4. Broadcast Category (type = 'broadcast')
-- System-wide announcements; bypasses message_templates, inserted directly into user_notifications
-- ------------------------------------------------------------------------------
-- sys_maintenance         : Scheduled system or node maintenance announcement
-- sys_node_down           : Unscheduled node outage alert
-- sys_activity_promo      : Promotional campaign or holiday deal announcement
-- sys_terms_updated       : Terms of service or privacy policy update notification
CREATE TYPE message_type AS ENUM('auth', 'business', 'ticket', 'broadcast');

CREATE TYPE notification_channel AS ENUM('email', 'telegram', 'site_msg', 'sms');

CREATE TABLE message_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    type message_type NOT NULL,
    channel notification_channel NOT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    subject varchar(255),
    content text NOT NULL,
    is_enable boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
);

CREATE UNIQUE INDEX uk_template_code_channel_lang ON message_templates (code, channel, LANGUAGE);

CREATE TYPE notification_category AS ENUM('system', 'ticket', 'broadcast');

CREATE TABLE user_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL DEFAULT 0,
    template_code varchar(64) NOT NULL,
    params jsonb,
    link_url varchar(255),
    is_urgent boolean NOT NULL DEFAULT FALSE,
    is_read boolean NOT NULL DEFAULT FALSE,
    expired_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_notifications_user_unread ON user_notifications (user_id, is_read, created_at DESC) WHERE user_id > 0;

CREATE INDEX idx_user_notifications_broadcast ON user_notifications (created_at DESC) WHERE user_id = 0;

CREATE TABLE user_read_announcements (
    user_id bigint NOT NULL,
    notification_id bigint NOT NULL,
    read_at timestamptz NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, notification_id)
);

CREATE TABLE notification_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL DEFAULT 0,
    channel notification_channel NOT NULL,
    template_code varchar(64) NOT NULL,
    recipient varchar(255) NOT NULL,
    title varchar(255),
    body text NOT NULL,
    status varchar(32) NOT NULL DEFAULT 'pending',
    error_reason text,
    sent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notification_logs_user_time ON notification_logs (user_id, created_at DESC);
CREATE INDEX idx_notification_logs_pending ON notification_logs (status, created_at) WHERE status = 'pending';