CREATE TYPE order_type AS ENUM('plan_purchase', 'plan_renew', 'plan_upgrade', 'traffic_reset_fee', 'traffic_addon', 'balance_recharge');
CREATE TYPE order_status AS ENUM('pending', 'processing', 'completed', 'cancelled', 'failed', 'refunded', 'disputed');

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    type order_type NOT NULL DEFAULT 'plan_purchase',
    status order_status NOT NULL DEFAULT 'pending',
    product_id bigint,
    product_price_id bigint,
    subscription_id bigint,
    renew_interval renew_interval,
    subtotal_amount DECIMAL(38, 18) NOT NULL,
    discount_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    balance_amount DECIMAL(38, 18) NOT NULL DEFAULT 0,
    total_amount DECIMAL(38, 18) NOT NULL,
    coupon_id bigint,
    coupon_snapshot jsonb DEFAULT '{}'::jsonb,
    price_snapshot jsonb DEFAULT '{}'::jsonb,
    payment_gateway_id bigint,
    payment_method varchar(32), -- balance/manual_transfer/epay/alipay_private/usdt_trc20
    paid_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_orders_order_no ON orders (order_no);
CREATE INDEX idx_orders_user_status_created ON orders (user_id, status, created_at DESC);