CREATE TYPE subscription_status AS ENUM('active', 'expired', 'exhausted', 'suspended', 'cancelled');

CREATE TABLE user_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_price_id bigint NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    status subscription_status NOT NULL DEFAULT 'active',
    billing_cycle billing_cycle NOT NULL,
    snap_limit_device_count int,
    snap_limit_speed_mbps int,
    snap_limit_speed_up_mbps int,
    snap_limit_speed_down_mbps int,
    snap_base_quota_bytes bigint NOT NULL,
    extra_quota_bytes bigint NOT NULL DEFAULT 0,
    started_at timestamptz NOT NULL DEFAULT NOW(),
    expired_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);


CREATE UNIQUE INDEX uk_user_subscriptions_uuid ON user_subscriptions (uuid);

CREATE INDEX idx_user_subscriptions_user_status ON user_subscriptions (user_id, status);

CREATE INDEX idx_user_subscriptions_expired_at ON user_subscriptions (expired_at) WHERE status = 'active';