CREATE TYPE subscription_status AS ENUM('active', 'expired', 'exhausted', 'suspended', 'cancelled');

CREATE TABLE subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_price_id bigint NOT NULL,
    token varchar(64) NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid (),
    status subscription_status NOT NULL DEFAULT 'active',
    reset_policy traffic_reset_policy NOT NULL,
    renew_interval renew_interval NOT NULL DEFAULT 'monthly',
    snap_limit_device_count int,
    snap_limit_speed_mbps int,
    snap_limit_speed_up_mbps int,
    snap_limit_speed_down_mbps int,
    snap_base_quota_bytes bigint NOT NULL,
    extra_quota_bytes bigint NOT NULL DEFAULT 0,
    started_at timestamptz NOT NULL DEFAULT NOW(),
    expired_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_subscriptions_token ON subscriptions (token);
CREATE UNIQUE INDEX uk_subscriptions_uuid ON subscriptions (uuid);
CREATE INDEX idx_subscriptions_user_status ON subscriptions (user_id, status);
CREATE INDEX idx_subscriptions_expired_at ON subscriptions (expired_at) WHERE status = 'active';