CREATE TYPE ticket_status AS ENUM('open', 'pending', 'resolved', 'closed');
CREATE TYPE ticket_priority AS ENUM('low', 'medium', 'high', 'urgent');

CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    status ticket_status NOT NULL DEFAULT 'open',
    priority ticket_priority NOT NULL DEFAULT 'medium',
    subscription_id bigint,
    subject varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tickets_user_id ON tickets (user_id);
CREATE INDEX idx_tickets_status ON tickets (status);
CREATE INDEX idx_tickets_priority ON tickets (priority);

CREATE TABLE ticket_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    user_id bigint NOT NULL,
    refer_id bigint,
    is_sensitive boolean NOT NULL DEFAULT FALSE,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ticket_messages_ticket_id ON ticket_messages (ticket_id);
CREATE INDEX idx_ticket_messages_user_id ON ticket_messages (user_id);

CREATE TABLE ticket_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    message_id bigint,
    user_id bigint NOT NULL,
    file_name varchar(255) NOT NULL,
    file_path varchar(512) NOT NULL,
    file_size bigint NOT NULL,
    file_type varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_attachments_ticket_id ON ticket_attachments (ticket_id);
CREATE INDEX idx_attachments_message_id ON ticket_attachments (message_id);
CREATE INDEX idx_attachments_user_id ON ticket_attachments (user_id);